server:
  port: 8002
  
spring:
  sleuth:
    sampler:
      probability: 1.0
  rabbitmq:
    addresses: localhost:5672
    virtual-host: app_vhost
    username: guest
    password: guest
  zipkin:
    baseUrl: http://localhost:9411/
    enabled: true
    sender:
      type: rabbit
  data:
    mongodb:
      database: dh1
      port: 27017

queue:
  series:
    name: serieQueue
  movies:
    name: movieQueue


message: hello from catalog-service

management:
  endpoints:
    web:
      exposure:
        include: '*'

# eureka config
eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance-id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
