eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    renewal-percent-threshold: 0.5
    expected-client-renewal-interval-seconds: 30
#  server:
#    wait-time-in-ms-when-sync-empty: 3000
spring:
  sleuth:
    sampler:
      probability: 1.0
  rabbitmq:
    addresses: localhost:5672
    username: guest
    password: guest
  zipkin:
    baseUrl: http://localhost:9411/
    enabled: true
    sender:
      type: rabbit

server:
  port: 8761
