server:
  port: 8080
spring:
  sleuth:
    sampler:
      probability: 1.0
  rabbitmq:
    addresses: localhost:5672
    username: guest
    password: guest
  zipkin:
    baseUrl: http://localhost:9411/
    enabled: true
    sender:
      type: rabbit
  cloud:
    gateway:
      routes:
        - id: route-catalog
          uri: lb://CATALOG-SERVICE/
          predicates:
          - Path=/**
          filters:
          - LoggingFilter
# eureka config
eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance-id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
