server:
  port: 0

queue:
  series:
    name: serieQueue
  movies:
    name: movieQueue

spring:
  sleuth:
    sampler:
      probability: 1.0
  rabbitmq:
    addresses: localhost:5672
    virtual-host: app_vhost
    username: guess
    password: guess
  zipkin:
    baseUrl: http://localhost:9411/
    enabled: true
    sender:
      type: rabbit
  data:
    mongodb:
      database: dh2
      port: 27017

message: hello from movie-service

management:
  endpoints:
    web:
      exposure:
        include: '*'
        
        
# eureka config
eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance-id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
